name: RSA256_test

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  python_test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/yodalee/rsa2048:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: python -m unittest discover script
